#!/usr/bin/env bash
# A script that installs nginx in an ubuntu machine
# nginx will listen on port 80
# when querying Nginx at its root using curl localhost
# it should return "Hello World!"
# /redirect_me should redirect to another page
# redirection must be 301 Moved Permanently
# 404 error page must custo to print something

new_redirect="\tlocation /redirect_me {\n\t\t return 301 https://linkedin.com/in/sanni-omoba;\n\t}\n"
input_after="=404;\n\t}"
new_input="\n\terror_page 404 /404.html;\n\tlocation /404.html {\n\t\tinternal;\n\t}\n"

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i "33s|.*|$new_redirect|" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "/$input_after/a $new_input" /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
