#!/usr/bin/env bash
# A script that installs nginx in an ubuntu machine
# nginx will listen on port 80
# when querying Nginx at its root using curl localhost
# it should return "Hello World!"
# /redirect_me should redirect to another page
# redirection must be 301 Moved Permanently

new_redirect="\tlocation /redirect_me {\n\t\t return 301 https://linkedin.com/in/sanni-omoba;\n\t}\n"


sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i "33s|.*|$new_redirect|" /etc/nginx/sites-available/default

sudo mkdir -p /var/www/error
echo "Ceci n'est pas une page" | sudo tee /var/www/error/404.html
sudo sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/error/;internal; }' /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
