#!/usr/bin/env bash
# install in a new Ubuntu machine HAProxy with the following requirements
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

two_servers="\\\nlisten webservers\n\tbind :80\n\tbalance roundrobin\n\tserver 220652-web-01 18.235.234.111:80 check\n\tserver 220652-web-02 100.25.181.230:80 check\n"

apt-get install --no-install-recommends -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get install -y haproxy=2.8.\*

sed -i -e "\$a ENABLED=1\n" /etc/default/haproxy


sudo cp /etc/haproxy/haproxy.cfg  /etc/haproxy/haproxy.cfg.backup

sed -i -e "\$a $two_servers" /etc/haproxy/haproxy.cfg

/etc/init.d/haproxy restart
