#!/usr/bin/env bash
# install in a new Ubuntu machine HAProxy with the following requirements
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

two_servers="\\\nlisten webservers\n\tbind :80\n\tbalance roundrobin\n\tserver 220652-web-01 18.235.234.111:80 check\n\tserver 220652-web-02 100.25.181.230:80 check\n"

sudo apt-get install --no-install-recommends -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*

sudo sed -i -e "$aENABLED=1\n" /etc/default/haproxy


sudo cp /etc/haproxy/haproxy.cfg  /etc/haproxy/haproxy.cfg.backup

sudo sed -i -e "$a\listen webservers\n\tbind :80\n\tbalance roundrobin\n\tserver 220652-web-01 18.235.234.111:80 check\n\tserver 220652-web-02 100.25.181.230:80 check\n" /etc/haproxy/haproxy.cfg

sudo /etc/init.d/haproxy restart
