#!/usr/bin/env bash
# A Bash init script that manages manage_my_process

daemon="./manage_my_process"
PIDFILE=/var/run/my_process.pid
function start() {
	$daemon &
	echo $! > $PIDFILE
	echo "manage_my_process started"
}
function stop() {
	kill "$(cat $PIDFILE)"
	rm $PIDFILE
	echo "manage_my_process stopped"
}
function restart() {
	kill "$(cat $PIDFILE)"
	rm $PIDFILE
	$daemon &
	echo $! > $PIDFILE
	echo "manage_my_process restarted"
}
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;

	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
