#!/usr/bin/env bash
#Configures an Ubuntu server with some requirements
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

i="/etc/hosts"
j=~/hosts.tmp
cp $i $j
echo "8.8.8.8	facebook.com" >> $j
sed -i 's/127.0.0.1/127.0.0.2/g' $j
cp -f $j $i
