#!/usr/bin/env bash
# Creates and RAS key pair
# private key named school, number of bits in the created key is 4096
# created key protected by passphrase betty

ssh-keygen -b 4096 -f school -N betty
